name: Deploy AI Maturity Scan - Vite Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Clean environment
        run: |
          echo "Cleaning dependency artifacts..."
          rm -rf node_modules package-lock.json || true
          npm cache clean --force
          echo "Environment cleaned successfully"
          
      - name: Install dependencies
        run: |
          echo "Installing Vite and dependencies..."
          npm install
          echo "Dependencies installed successfully"
          
      - name: Verify Vite installation
        run: |
          echo "Verifying Vite installation..."
          if [ -f "node_modules/.bin/vite" ]; then
            echo "✅ Vite found"
            npx vite --version
          else
            echo "❌ Vite not found"
            exit 1
          fi
          
      - name: Build application with Vite
        run: |
          echo "Starting Vite build..."
          npm run build
          echo "Vite build completed successfully!"
        env:
          NODE_ENV: production
          VITE_GITHUB_TOKEN: ${{ secrets.DATA_STORAGE }}
          VITE_ADMIN_PASSWORD: ${{ secrets.REACT_APP_ADMIN_PASSWORD }}
        
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ -d "build" ]; then
            echo "✅ Build directory created"
            echo "Build contents:"
            ls -la build/
            echo "Build size:"
            du -sh build/
            echo "Static files:"
            find build -name "*.js" -o -name "*.css" -o -name "*.html" | head -10
          else
            echo "❌ Build directory not found"
            exit 1
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
