name: Deploy AI Maturity Scan - Bulletproof Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Remove cache to avoid lock file issues
          
      - name: Clean environment completely
        run: |
          echo "Cleaning all dependency artifacts..."
          rm -rf node_modules package-lock.json yarn.lock pnpm-lock.yaml || true
          npm cache clean --force
          echo "Environment cleaned successfully"
          
      - name: Install dependencies fresh
        run: |
          echo "Installing dependencies from scratch..."
          npm install --no-package-lock --legacy-peer-deps --no-audit --no-fund
          echo "Dependencies installed successfully"
          
      - name: Verify installation
        run: |
          echo "Verifying React Scripts installation..."
          if [ -f "node_modules/.bin/react-scripts" ]; then
            echo "✅ react-scripts found"
          else
            echo "❌ react-scripts not found"
            exit 1
          fi
          echo "Node modules structure:"
          ls -la node_modules/ | head -20
          
      - name: Build application
        run: |
          echo "Starting React build..."
          npm run build
          echo "Build completed successfully!"
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          NODE_OPTIONS: "--max-old-space-size=4096"
          REACT_APP_GITHUB_TOKEN: ${{ secrets.DATA_STORAGE }}
          REACT_APP_ADMIN_PASSWORD: ${{ secrets.REACT_APP_ADMIN_PASSWORD }}
        
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ -d "build" ]; then
            echo "✅ Build directory created"
            echo "Build contents:"
            ls -la build/
            echo "Build size:"
            du -sh build/
            echo "Static files:"
            find build -name "*.js" -o -name "*.css" -o -name "*.html" | head -10
          else
            echo "❌ Build directory not found"
            exit 1
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
