name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Configure npm for reliability
        run: |
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retries 5
          npm config set registry https://registry.npmjs.org/

      - name: Install dependencies with retry
        run: |
          npm install --no-audit --no-fund --prefer-offline || \
          (echo "First attempt failed, clearing cache and retrying..." && \
           npm cache clean --force && \
           npm install --no-audit --no-fund --force) || \
          (echo "Second attempt failed, trying with legacy peer deps..." && \
           npm install --no-audit --no-fund --force --legacy-peer-deps)
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
