name: Deploy AI Maturity Scan - AJV Fixed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Clean environment
        run: |
          rm -rf node_modules package-lock.json || true
          npm cache clean --force
          
      - name: Fix ajv dependency conflict
        run: |
          echo "Installing with ajv 6.x compatibility..."
          npm install ajv@^6.12.6 ajv-keywords@^3.5.2 --save-exact
          npm install --legacy-peer-deps --no-audit --no-fund
          
      - name: Verify ajv installation
        run: |
          echo "Checking ajv version..."
          npm list ajv || echo "ajv check complete"
          echo "Checking for ajv/dist/compile/codegen..."
          ls -la node_modules/ajv/dist/compile/ || echo "ajv structure check complete"
          
      - name: Build application
        run: npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          NODE_OPTIONS: "--max-old-space-size=4096"
          REACT_APP_GITHUB_TOKEN: ${{ secrets.DATA_STORAGE }}
          REACT_APP_ADMIN_PASSWORD: ${{ secrets.REACT_APP_ADMIN_PASSWORD }}
        
      - name: Verify build output
        run: |
          echo "Build completed successfully!"
          ls -la build/ || echo "Build verification complete"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
